### get products
get http://localhost:3000/products

### get product
get http://localhost:3000/products/2

### post product
post http://localhost:3000/products
Content-Type: application/json

{
    "id": 4,
    "name": "Áru4",
    "quantity": 40,
    "price": 4500
}

### delete product
delete http://localhost:3000/products/4

### put product
put http://localhost:3000/products/3
Content-Type: application/json

{
    "id": 3,
    "name": "Áru3 3xx",
    "quantity": 533,
    "price": 55032
}


